token = "[your token here]"
prefix = "[your prefix here]"

# Put your guild-specific configuration(s) here

# Example:

# [guilds.guild_id]
# thresholds = { minutes = points, ... }
# bonus_role = [your bonus role id]
# daily_points = [points]
# picture_channel = [channel id] (optional)
# lottery_channel = [channel id] (optional)
# door_member = [member id]

# [guilds.guild_id.admins]
# users = [ user_id, ... ]
# roles = [ role_id, ... ]
